"""create invoices table for invoice ocr and add invoice_linked ledger source

Revision ID: 03c3604959d2
Revises: 3168a5b15e0f
Create Date: 2026-08-21 15:18:37.279726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c3604959d2'
down_revision: Union[str, None] = '3168a5b15e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate does NOT detect a new value added to an EXISTING
    # PostgreSQL native enum (a known Alembic limitation) - added here
    # manually.
    op.execute("ALTER TYPE ledger_entry_source ADD VALUE 'invoice_linked'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('image_storage_key', sa.String(length=500), nullable=False),
    sa.Column('ocr_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='invoice_ocr_status'), nullable=False),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('ocr_confidence', sa.Enum('high', 'medium', 'low', name='invoice_ocr_confidence'), nullable=True),
    sa.Column('ocr_unavailable_reason', sa.Text(), nullable=True),
    sa.Column('extracted_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('extracted_date', sa.Date(), nullable=True),
    sa.Column('extracted_vendor_name', sa.String(length=200), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('confirmed_date', sa.Date(), nullable=True),
    sa.Column('confirmed_vendor_name', sa.String(length=200), nullable=True),
    sa.Column('confirmed_category', sa.String(length=50), nullable=True),
    sa.Column('linked_ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_ledger_entry_id'], ['ledger_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_crop_cycle_id'), 'invoices', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_invoices_farmer_id'), 'invoices', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_invoices_ocr_status'), 'invoices', ['ocr_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_ocr_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_farmer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_crop_cycle_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###

    # Enum types are not dropped by autogenerate - proactively fixed here.
    bind = op.get_bind()
    sa.Enum(name='invoice_ocr_confidence').drop(bind, checkfirst=True)
    sa.Enum(name='invoice_ocr_status').drop(bind, checkfirst=True)

    # PostgreSQL has no ALTER TYPE ... DROP VALUE - removing
    # 'invoice_linked' from ledger_entry_source requires the standard
    # rename/recreate/cast dance. This will correctly FAIL if any
    # ledger_entries row actually has source='invoice_linked' at
    # downgrade time (the USING cast has nothing to map that value to) -
    # which is the right behavior: you cannot downgrade past the point
    # where real data depends on the value being removed.
    op.execute("ALTER TYPE ledger_entry_source RENAME TO ledger_entry_source_old")
    op.execute("CREATE TYPE ledger_entry_source AS ENUM ('manual', 'sale_linked')")
    op.execute(
        "ALTER TABLE ledger_entries ALTER COLUMN source TYPE ledger_entry_source "
        "USING source::text::ledger_entry_source"
    )
    op.execute("DROP TYPE ledger_entry_source_old")
