"""create crop cost estimates table and add stage tag to ledger entries

Revision ID: 0f96c82c2a21
Revises: 03c3604959d2
Create Date: 2026-08-21 15:42:55.492121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f96c82c2a21'
down_revision: Union[str, None] = '03c3604959d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_cost_estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('crop_stage_definition_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_stage_definition_id'], ['crop_stage_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cost_estimates_crop_cycle_id'), 'crop_cost_estimates', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_crop_cost_estimates_crop_stage_definition_id'), 'crop_cost_estimates', ['crop_stage_definition_id'], unique=False)
    op.create_index(op.f('ix_crop_cost_estimates_farmer_id'), 'crop_cost_estimates', ['farmer_id'], unique=False)
    op.add_column('ledger_entries', sa.Column('crop_stage_definition_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ledger_entries_crop_stage_definition_id'), 'ledger_entries', ['crop_stage_definition_id'], unique=False)
    op.create_foreign_key('ledger_entries_crop_stage_definition_id_fkey', 'ledger_entries', 'crop_stage_definitions', ['crop_stage_definition_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ledger_entries_crop_stage_definition_id_fkey', 'ledger_entries', type_='foreignkey')
    op.drop_index(op.f('ix_ledger_entries_crop_stage_definition_id'), table_name='ledger_entries')
    op.drop_column('ledger_entries', 'crop_stage_definition_id')
    op.drop_index(op.f('ix_crop_cost_estimates_farmer_id'), table_name='crop_cost_estimates')
    op.drop_index(op.f('ix_crop_cost_estimates_crop_stage_definition_id'), table_name='crop_cost_estimates')
    op.drop_index(op.f('ix_crop_cost_estimates_crop_cycle_id'), table_name='crop_cost_estimates')
    op.drop_table('crop_cost_estimates')
    # ### end Alembic commands ###
