"""create assistant conversation feedback preference and knowledge tables

Revision ID: 30cdfa913a3c
Revises: 8b8d84c1b065
Create Date: 2026-08-14 01:06:19.126195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30cdfa913a3c'
down_revision: Union[str, None] = '8b8d84c1b065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_conversations_farmer_id'), 'assistant_conversations', ['farmer_id'], unique=False)
    op.create_table('assistant_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('response_mode', sa.Enum('simple', 'detailed', name='assistant_response_mode'), nullable=False),
    sa.Column('voice_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('proactive_suggestions_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id')
    )
    op.create_table('knowledge_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('license_status', sa.Enum('open_license', 'public_domain', 'official_government_source', 'internal_approved_summary', name='knowledge_license_status'), nullable=False),
    sa.Column('version_date', sa.Date(), nullable=False),
    sa.Column('last_reviewed_at', sa.Date(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_topic'), 'knowledge_entries', ['topic'], unique=False)
    op.create_table('assistant_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'assistant', name='assistant_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('tools_called', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Enum('high_confidence', 'medium_confidence', 'low_confidence', name='assistant_confidence_level'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_messages_conversation_id'), 'assistant_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_assistant_messages_intent'), 'assistant_messages', ['intent'], unique=False)
    op.create_table('ai_evaluation_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('grounded', sa.Boolean(), nullable=True),
    sa.Column('safety_flag_triggered', sa.Boolean(), nullable=False),
    sa.Column('farmer_reported_issue', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['assistant_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assistant_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('helpful', 'not_helpful', 'wrong', 'need_expert', name='assistant_feedback_type'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['assistant_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_feedback_message_id'), 'assistant_feedback', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_feedback_message_id'), table_name='assistant_feedback')
    op.drop_table('assistant_feedback')
    op.drop_table('ai_evaluation_records')
    op.drop_index(op.f('ix_assistant_messages_intent'), table_name='assistant_messages')
    op.drop_index(op.f('ix_assistant_messages_conversation_id'), table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_index(op.f('ix_knowledge_entries_topic'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_table('assistant_preferences')
    op.drop_index(op.f('ix_assistant_conversations_farmer_id'), table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    # ### end Alembic commands ###

    # Enum types are not dropped by autogenerate - proactively fixed here
    # based on the lesson from every prior migration (see docs/DATABASE.md).
    bind = op.get_bind()
    sa.Enum(name='assistant_response_mode').drop(bind, checkfirst=True)
    sa.Enum(name='knowledge_license_status').drop(bind, checkfirst=True)
    sa.Enum(name='assistant_message_role').drop(bind, checkfirst=True)
    sa.Enum(name='assistant_confidence_level').drop(bind, checkfirst=True)
    sa.Enum(name='assistant_feedback_type').drop(bind, checkfirst=True)
