"""create ledger entries table for digital crop financial ledger

Revision ID: 3168a5b15e0f
Revises: 3ca0a1041727
Create Date: 2026-08-21 14:55:31.520139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3168a5b15e0f'
down_revision: Union[str, None] = '3ca0a1041727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('expense', 'revenue', name='ledger_entry_type'), nullable=False),
    sa.Column('category', sa.Enum('seed', 'fertilizer', 'pesticide', 'labor', 'equipment', 'irrigation', 'land_rent', 'transport', 'harvest_sale', 'other', name='ledger_category'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'sale_linked', name='ledger_entry_source'), nullable=False),
    sa.Column('linked_sale_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_sale_id'], ['sale_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_sale_id', name='uq_ledger_entries_linked_sale_id')
    )
    op.create_index(op.f('ix_ledger_entries_crop_cycle_id'), 'ledger_entries', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_entry_type'), 'ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_farmer_id'), 'ledger_entries', ['farmer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_farmer_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_crop_cycle_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###

    # Enum types are not dropped by autogenerate - proactively fixed here
    # based on the lesson from every prior migration.
    bind = op.get_bind()
    sa.Enum(name='ledger_entry_source').drop(bind, checkfirst=True)
    sa.Enum(name='ledger_category').drop(bind, checkfirst=True)
    sa.Enum(name='ledger_entry_type').drop(bind, checkfirst=True)
