"""create soil samples and soil test results tables for D20 soil testing domain

Revision ID: 381e2dc405e4
Revises: 4ab51c60125d
Create Date: 2026-09-06 01:43:12.238802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '381e2dc405e4'
down_revision: Union[str, None] = '4ab51c60125d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('lab_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_samples_farmer_id'), 'soil_samples', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_soil_samples_plot_id'), 'soil_samples', ['plot_id'], unique=False)
    op.create_table('soil_test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('soil_sample_id', sa.UUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('ph_value', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('nitrogen_kg_per_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phosphorus_kg_per_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('potassium_kg_per_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('organic_carbon_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ec_ds_per_m', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('micronutrients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_storage_key', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ph_value IS NULL OR (ph_value >= 0 AND ph_value <= 14)', name='ck_soil_test_results_ph_range'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['soil_sample_id'], ['soil_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_test_results_farmer_id'), 'soil_test_results', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_soil_test_results_soil_sample_id'), 'soil_test_results', ['soil_sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soil_test_results_soil_sample_id'), table_name='soil_test_results')
    op.drop_index(op.f('ix_soil_test_results_farmer_id'), table_name='soil_test_results')
    op.drop_table('soil_test_results')
    op.drop_index(op.f('ix_soil_samples_plot_id'), table_name='soil_samples')
    op.drop_index(op.f('ix_soil_samples_farmer_id'), table_name='soil_samples')
    op.drop_table('soil_samples')
    # ### end Alembic commands ###
