"""add crop stage timing fields and crop cycle stage history

Phase 2 infrastructure only: nullable relative-timing columns on
CropStageDefinition (unpopulated by default - no agronomic dataset
exists in this repository to seed them from), and a new append-only
CropCycleStageHistory table recording actual cultivation_status
transitions. No columns removed, no data touched, does not modify the
Phase 0 or Phase 1 migrations.

status uses its own distinct enum type (crop_cycle_stage_history_status)
rather than reusing crop_cycles' existing cultivation_status type -
autogenerate emits a plain CREATE TYPE for a reused name, which fails
with "already exists"; a dedicated type avoids that entirely and matches
this codebase's existing convention of one enum type per column context
(no other model reuses another model's enum type).

Revision ID: 3ca0a1041727
Revises: a99bd945587b
Create Date: 2026-08-18 07:17:50.465252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca0a1041727'
down_revision: Union[str, None] = 'a99bd945587b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_cycle_stage_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'sown', 'growing', 'flowering', 'fruiting', 'ready_for_harvest', 'harvested', 'cancelled', name='crop_cycle_stage_history_status'), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cycle_stage_history_crop_cycle_id'), 'crop_cycle_stage_history', ['crop_cycle_id'], unique=False)
    op.add_column('crop_stage_definitions', sa.Column('typical_days_from_sowing_start', sa.Integer(), nullable=True))
    op.add_column('crop_stage_definitions', sa.Column('typical_days_from_sowing_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop_stage_definitions', 'typical_days_from_sowing_end')
    op.drop_column('crop_stage_definitions', 'typical_days_from_sowing_start')
    op.drop_index(op.f('ix_crop_cycle_stage_history_crop_cycle_id'), table_name='crop_cycle_stage_history')
    op.drop_table('crop_cycle_stage_history')
    # ### end Alembic commands ###

    # Enum type is not dropped by autogenerate - proactively fixed here
    # based on the lesson from every prior migration in this codebase
    # (see the tasks and soil-report migrations).
    bind = op.get_bind()
    sa.Enum(name='crop_cycle_stage_history_status').drop(bind, checkfirst=True)
