"""create irrigation records table for D18-06 irrigation activity

Revision ID: 4ab51c60125d
Revises: e5f6a7b8c9d0
Create Date: 2026-09-05 23:16:37.699380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4ab51c60125d'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irrigation_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('irrigation_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('volume_liters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source', postgresql.ENUM('rain_fed', 'borewell', 'canal', 'drip', 'sprinkler', 'other', name='irrigation_source', create_type=False), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('failure_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_records_crop_cycle_id'), 'irrigation_records', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_irrigation_records_farmer_id'), 'irrigation_records', ['farmer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_irrigation_records_farmer_id'), table_name='irrigation_records')
    op.drop_index(op.f('ix_irrigation_records_crop_cycle_id'), table_name='irrigation_records')
    op.drop_table('irrigation_records')
    # ### end Alembic commands ###
