"""create disease crop stage ai model registry and ai analysis tables

Revision ID: 4cac6105f1a7
Revises: 8b83c52b7a23
Create Date: 2026-08-13 00:10:54.856116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cac6105f1a7'
down_revision: Union[str, None] = '8b83c52b7a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('input_size', sa.String(length=50), nullable=True),
    sa.Column('supported_crop_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_ai_model_registry_name_version')
    )
    op.create_table('crop_stage_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('stage_code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'stage_code', name='uq_crop_stage_definitions_crop_code')
    )
    op.create_index(op.f('ix_crop_stage_definitions_crop_id'), 'crop_stage_definitions', ['crop_id'], unique=False)
    op.create_table('disease_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('disease_name', sa.String(length=150), nullable=False),
    sa.Column('local_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disease_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'disease_name', name='uq_disease_classes_crop_name')
    )
    op.create_index(op.f('ix_disease_classes_crop_id'), 'disease_classes', ['crop_id'], unique=False)
    op.create_table('ai_analysis_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_photo_session_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_photo_session_id'], ['crop_photo_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_sessions_crop_cycle_id'), 'ai_analysis_sessions', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_sessions_crop_photo_session_id'), 'ai_analysis_sessions', ['crop_photo_session_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_sessions_farmer_id'), 'ai_analysis_sessions', ['farmer_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_photo_id', sa.UUID(), nullable=False),
    sa.Column('analysis_session_id', sa.UUID(), nullable=True),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('model_registry_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_class', sa.String(length=150), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('top_k_predictions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_status', sa.Enum('healthy', 'disease_detected', 'unknown', 'low_confidence', 'crop_mismatch', 'processing', 'failed', 'ai_unavailable', name='ai_result_status'), nullable=False),
    sa.Column('analysis_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ai_analysis_status'), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('inference_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('preprocessing_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['ai_analysis_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_photo_id'], ['crop_photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_registry_id'], ['ai_model_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_analysis_session_id'), 'ai_analyses', ['analysis_session_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_analysis_status'), 'ai_analyses', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_ai_analyses_crop_cycle_id'), 'ai_analyses', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_crop_photo_id'), 'ai_analyses', ['crop_photo_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_farmer_id'), 'ai_analyses', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_result_status'), 'ai_analyses', ['result_status'], unique=False)
    op.create_table('ai_crop_stage_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_photo_id', sa.UUID(), nullable=True),
    sa.Column('predicted_stage_code', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('analysis_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ai_analysis_status'), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_photo_id'], ['crop_photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_crop_stage_results_crop_cycle_id'), 'ai_crop_stage_results', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_ai_crop_stage_results_farmer_id'), 'ai_crop_stage_results', ['farmer_id'], unique=False)
    # ### end Alembic commands ###

    # --- Seed data ---

    # The "no real model configured" registry row (Requirement 45's honest
    # AI_NOT_CONFIGURED state, made queryable rather than a magic string).
    # Deliberately is_active=false: there IS no active model.
    op.execute(
        """
        INSERT INTO ai_model_registry (id, name, version, framework, license, input_size, supported_crop_ids, is_active, created_at)
        VALUES (gen_random_uuid(), 'crop_disease_baseline', 'unconfigured-0.0', NULL, NULL, NULL, '[]'::jsonb, false, now())
        """
    )

    # Illustrative disease classes for the crops seeded in the Farm/Plot/
    # Crop phase. NOT tied to any working model - see docs/DISEASE_MODEL.md.
    op.execute(
        """
        INSERT INTO disease_classes (id, crop_id, disease_name, local_names, scientific_name, description, severity, is_active, created_at, updated_at)
        SELECT gen_random_uuid(), id, 'Healthy', '{"hi": "स्वस्थ"}'::jsonb, NULL, 'No visible disease symptoms.', NULL, true, now(), now()
        FROM crop_master WHERE name = 'Tomato'
        UNION ALL
        SELECT gen_random_uuid(), id, 'Early Blight', '{"hi": "अगेती झुलसा"}'::jsonb, 'Alternaria solani', 'Dark concentric-ring spots on older leaves.', 'medium', true, now(), now()
        FROM crop_master WHERE name = 'Tomato'
        UNION ALL
        SELECT gen_random_uuid(), id, 'Late Blight', '{"hi": "पछेती झुलसा"}'::jsonb, 'Phytophthora infestans', 'Water-soaked lesions that spread rapidly in cool, wet weather.', 'high', true, now(), now()
        FROM crop_master WHERE name = 'Tomato'
        UNION ALL
        SELECT gen_random_uuid(), id, 'Leaf Mold', NULL::jsonb, 'Passalora fulva', 'Pale spots on upper leaf surface, olive-green mold beneath.', 'medium', true, now(), now()
        FROM crop_master WHERE name = 'Tomato'
        UNION ALL
        SELECT gen_random_uuid(), id, 'Healthy', '{"hi": "स्वस्थ"}'::jsonb, NULL, 'No visible disease symptoms.', NULL, true, now(), now()
        FROM crop_master WHERE name = 'Rice'
        UNION ALL
        SELECT gen_random_uuid(), id, 'Bacterial Leaf Blight', NULL::jsonb, 'Xanthomonas oryzae', 'Water-soaked stripes that turn yellow-white along leaf veins.', 'high', true, now(), now()
        FROM crop_master WHERE name = 'Rice'
        """
    )

    # Generic crop-stage set applied to the same two illustrative crops.
    # The schema supports per-crop divergence starting with the next crop
    # added - this seed doesn't yet demonstrate that, only the capability.
    op.execute(
        """
        INSERT INTO crop_stage_definitions (id, crop_id, stage_code, display_name, sequence_order, is_active, created_at, updated_at)
        SELECT gen_random_uuid(), id, stage_code, display_name, sequence_order, true, now(), now()
        FROM crop_master
        CROSS JOIN (VALUES
            ('seedling', 'Seedling', 1),
            ('vegetative', 'Vegetative Growth', 2),
            ('flowering', 'Flowering', 3),
            ('fruiting', 'Fruiting', 4),
            ('maturation', 'Maturation', 5),
            ('ready_for_harvest', 'Ready for Harvest', 6)
        ) AS stages(stage_code, display_name, sequence_order)
        WHERE crop_master.name IN ('Tomato', 'Rice')
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_crop_stage_results_farmer_id'), table_name='ai_crop_stage_results')
    op.drop_index(op.f('ix_ai_crop_stage_results_crop_cycle_id'), table_name='ai_crop_stage_results')
    op.drop_table('ai_crop_stage_results')
    op.drop_index(op.f('ix_ai_analyses_result_status'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_farmer_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_crop_photo_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_crop_cycle_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_status'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_session_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_ai_analysis_sessions_farmer_id'), table_name='ai_analysis_sessions')
    op.drop_index(op.f('ix_ai_analysis_sessions_crop_photo_session_id'), table_name='ai_analysis_sessions')
    op.drop_index(op.f('ix_ai_analysis_sessions_crop_cycle_id'), table_name='ai_analysis_sessions')
    op.drop_table('ai_analysis_sessions')
    op.drop_index(op.f('ix_disease_classes_crop_id'), table_name='disease_classes')
    op.drop_table('disease_classes')
    op.drop_index(op.f('ix_crop_stage_definitions_crop_id'), table_name='crop_stage_definitions')
    op.drop_table('crop_stage_definitions')
    op.drop_table('ai_model_registry')
    # ### end Alembic commands ###

    # Enum types are not dropped by autogenerate - proactively fixed here
    # based on the lesson from prior migrations (see docs/DATABASE.md).
    bind = op.get_bind()
    sa.Enum(name='ai_result_status').drop(bind, checkfirst=True)
    sa.Enum(name='ai_analysis_status').drop(bind, checkfirst=True)
