"""create product catalog dealer pricing order payment delivery and dispute tables

Revision ID: 56f3c02490a8
Revises: dc30b6c2b356
Create Date: 2026-08-13 05:17:55.935131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56f3c02490a8'
down_revision: Union[str, None] = 'dc30b6c2b356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('seed', 'fertilizer', 'bio_input', 'pest_control_product', 'crop_protection_product', 'equipment', 'other_agricultural_input', name='product_category'), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('active_ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pack_size_value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('pack_size_unit', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_information', sa.Text(), nullable=True),
    sa.Column('regulatory_info', sa.Text(), nullable=True),
    sa.Column('image_storage_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', 'suspended', 'recalled', name='product_status'), nullable=False),
    sa.Column('is_test_product', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('reference_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('official_source', 'authorized_market_source', 'manufacturer_reference', 'verified_market_data', 'admin_entered_reference', name='reference_price_source_type'), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('region', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_prices_effective_date'), 'reference_prices', ['effective_date'], unique=False)
    op.create_index(op.f('ix_reference_prices_product_id'), 'reference_prices', ['product_id'], unique=False)
    op.create_table('dealer_business_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id')
    )
    op.create_table('dealer_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_area', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dealer_id', 'product_id', name='uq_dealer_products_dealer_product')
    )
    op.create_index(op.f('ix_dealer_products_dealer_id'), 'dealer_products', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_products_expiry_date'), 'dealer_products', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_dealer_products_product_id'), 'dealer_products', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_confirmation', 'confirmed', 'payment_pending', 'paid', 'accepted_by_dealer', 'preparing', 'ready_for_dispatch', 'dispatched', 'out_for_delivery', 'delivered', 'cancelled', 'rejected', 'refund_pending', 'refunded', 'disputed', name='order_status'), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delivery_fee_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delivery_area', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('rejection_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['professional_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_orders_dealer_id'), 'orders', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_orders_farmer_id'), 'orders', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('dealer_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dealer_product_id', sa.UUID(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_product_id'], ['dealer_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_price_history_dealer_product_id'), 'dealer_price_history', ['dealer_product_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'failed', 'returned', name='delivery_status'), nullable=False),
    sa.Column('estimated_delivery_date', sa.Date(), nullable=True),
    sa.Column('tracking_note', sa.Text(), nullable=True),
    sa.Column('weather_delay_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    op.create_table('order_disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('wrong_product', 'missing_item', 'damaged_product', 'payment_issue', 'delivery_issue', 'unexpected_charge', 'product_authenticity_concern', name='dispute_reason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_review', 'resolved', 'rejected', 'escalated', name='dispute_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_disputes_order_id'), 'order_disputes', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_disputes_status'), 'order_disputes', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('dealer_product_id', sa.UUID(), nullable=False),
    sa.Column('product_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_item_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_product_id'], ['dealer_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'dealer_product_id', name='uq_order_items_order_dealer_product')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('sandbox', 'upi', 'card', 'net_banking', 'cash_on_delivery', name='payment_provider'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'cancelled', 'timeout', name='payment_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('price_anomaly_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dealer_product_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('high', 'unusual', 'review_required', name='price_anomaly_level'), nullable=False),
    sa.Column('dealer_price_at_detection', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_price_at_detection', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dealer_product_id'], ['dealer_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_anomaly_flags_dealer_product_id'), 'price_anomaly_flags', ['dealer_product_id'], unique=False)
    op.create_index(op.f('ix_price_anomaly_flags_level'), 'price_anomaly_flags', ['level'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('dispute_id', sa.UUID(), nullable=True),
    sa.Column('refund_type', sa.Enum('full_refund', 'partial_refund', 'no_refund', name='refund_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'rejected', name='refund_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dispute_id'], ['order_disputes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    # ### end Alembic commands ###

    # --- Seed data: illustrative, test-marked products + reference
    # prices, same honesty pattern as every prior phase's seed data (not
    # authoritative, exists to exercise the schema/API end-to-end). ---
    op.execute(
        """
        INSERT INTO products (id, name, category, manufacturer, pack_size_value, pack_size_unit, description, status, is_test_product, created_at, updated_at)
        VALUES
        (gen_random_uuid(), 'Test Fungicide A 500ml', 'crop_protection_product', 'Test Manufacturer Ltd', 500, 'ml', 'Illustrative test product for fungal disease management.', 'approved', true, now(), now()),
        (gen_random_uuid(), 'Test Fungicide A 1L', 'crop_protection_product', 'Test Manufacturer Ltd', 1000, 'ml', 'Illustrative test product for fungal disease management (larger pack).', 'approved', true, now(), now()),
        (gen_random_uuid(), 'Test NPK Fertilizer 50kg', 'fertilizer', 'Test Agro Ltd', 50, 'kg', 'Illustrative general-purpose fertilizer.', 'approved', true, now(), now()),
        (gen_random_uuid(), 'Test Tomato Seeds 100g', 'seed', 'Test Seeds Co', 100, 'g', 'Illustrative hybrid tomato seed pack.', 'approved', true, now(), now()),
        (gen_random_uuid(), 'Test Pending Product', 'other_agricultural_input', NULL, 1, 'unit', 'Illustrative product awaiting admin approval.', 'pending_review', true, now(), now())
        """
    )

    # A reference price for the first seeded (approved) product, so price
    # comparison/anomaly logic has something real to compare against in
    # dev/testing without needing a live external price feed.
    op.execute(
        """
        INSERT INTO reference_prices (id, product_id, price, source_type, source_name, effective_date, retrieved_at, created_at)
        SELECT gen_random_uuid(), id, 250.00, 'admin_entered_reference', 'Illustrative seed reference price', CURRENT_DATE, now(), now()
        FROM products WHERE name = 'Test Fungicide A 500ml'
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_price_anomaly_flags_level'), table_name='price_anomaly_flags')
    op.drop_index(op.f('ix_price_anomaly_flags_dealer_product_id'), table_name='price_anomaly_flags')
    op.drop_table('price_anomaly_flags')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_disputes_status'), table_name='order_disputes')
    op.drop_index(op.f('ix_order_disputes_order_id'), table_name='order_disputes')
    op.drop_table('order_disputes')
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_dealer_price_history_dealer_product_id'), table_name='dealer_price_history')
    op.drop_table('dealer_price_history')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_farmer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_dealer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_dealer_products_product_id'), table_name='dealer_products')
    op.drop_index(op.f('ix_dealer_products_expiry_date'), table_name='dealer_products')
    op.drop_index(op.f('ix_dealer_products_dealer_id'), table_name='dealer_products')
    op.drop_table('dealer_products')
    op.drop_table('dealer_business_profiles')
    op.drop_index(op.f('ix_reference_prices_product_id'), table_name='reference_prices')
    op.drop_index(op.f('ix_reference_prices_effective_date'), table_name='reference_prices')
    op.drop_table('reference_prices')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###

    # Enum types are not dropped by autogenerate - proactively fixed here
    # based on the lesson from every prior migration (see docs/DATABASE.md).
    bind = op.get_bind()
    sa.Enum(name='refund_status').drop(bind, checkfirst=True)
    sa.Enum(name='refund_type').drop(bind, checkfirst=True)
    sa.Enum(name='dispute_status').drop(bind, checkfirst=True)
    sa.Enum(name='dispute_reason').drop(bind, checkfirst=True)
    sa.Enum(name='payment_status').drop(bind, checkfirst=True)
    sa.Enum(name='payment_provider').drop(bind, checkfirst=True)
    sa.Enum(name='delivery_status').drop(bind, checkfirst=True)
    sa.Enum(name='order_status').drop(bind, checkfirst=True)
    sa.Enum(name='price_anomaly_level').drop(bind, checkfirst=True)
    sa.Enum(name='reference_price_source_type').drop(bind, checkfirst=True)
    sa.Enum(name='product_status').drop(bind, checkfirst=True)
    sa.Enum(name='product_category').drop(bind, checkfirst=True)
