"""create farm plot crop master and crop cycle tables

Revision ID: 6bcb8d62ff76
Revises: 06dc63fcf105
Create Date: 2026-08-12 12:33:06.816985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bcb8d62ff76'
down_revision: Union[str, None] = '06dc63fcf105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('local_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('crop_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crop_master_category'), 'crop_master', ['category'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('farm_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('area_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('area_unit', sa.Enum('acre', 'hectare', 'gunta', 'cent', 'square_meter', name='area_unit'), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='farm_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('area_value > 0', name='ck_farms_area_value_positive'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farmer_id'), 'farms', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farms_status'), 'farms', ['status'], unique=False)
    op.create_table('plots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('plot_name', sa.String(length=200), nullable=False),
    sa.Column('area_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('area_unit', sa.Enum('acre', 'hectare', 'gunta', 'cent', 'square_meter', name='area_unit'), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('irrigation_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='farm_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('area_value > 0', name='ck_plots_area_value_positive'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plots_farm_id'), 'plots', ['farm_id'], unique=False)
    op.create_index(op.f('ix_plots_status'), 'plots', ['status'], unique=False)
    op.create_table('crop_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('season', sa.Enum('kharif', 'rabi', 'zaid', 'perennial', 'other', name='crop_season'), nullable=True),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('cultivation_status', sa.Enum('planned', 'sown', 'growing', 'flowering', 'fruiting', 'ready_for_harvest', 'harvested', 'cancelled', name='cultivation_status'), nullable=False),
    sa.Column('seed_variety', sa.String(length=150), nullable=True),
    sa.Column('ai_suggested_stage', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_observation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_harvest_date IS NULL OR actual_harvest_date >= sowing_date', name='ck_crop_cycles_actual_harvest_after_sowing'),
    sa.CheckConstraint('expected_harvest_date IS NULL OR expected_harvest_date >= sowing_date', name='ck_crop_cycles_expected_harvest_after_sowing'),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cycles_crop_id'), 'crop_cycles', ['crop_id'], unique=False)
    op.create_index(op.f('ix_crop_cycles_cultivation_status'), 'crop_cycles', ['cultivation_status'], unique=False)
    op.create_index(op.f('ix_crop_cycles_expected_harvest_date'), 'crop_cycles', ['expected_harvest_date'], unique=False)
    op.create_index(op.f('ix_crop_cycles_plot_id'), 'crop_cycles', ['plot_id'], unique=False)
    op.create_index(op.f('ix_crop_cycles_sowing_date'), 'crop_cycles', ['sowing_date'], unique=False)
    # ### end Alembic commands ###

    # Seed a small, illustrative crop master list for local dev/testing.
    # This is NOT an authoritative agricultural dataset - just enough to
    # exercise crop selection end-to-end. Expand deliberately later, one
    # verified entry at a time, per docs/CROP_MODULE.md.
    op.execute(
        """
        INSERT INTO crop_master (id, name, local_names, scientific_name, category, is_active, created_at, updated_at)
        VALUES
        (gen_random_uuid(), 'Rice', '{"hi": "चावल", "ml": "നെല്ല്", "ta": "நெல்"}', 'Oryza sativa', 'cereal', true, now(), now()),
        (gen_random_uuid(), 'Wheat', '{"hi": "गेहूं"}', 'Triticum aestivum', 'cereal', true, now(), now()),
        (gen_random_uuid(), 'Maize', '{"hi": "मक्का"}', 'Zea mays', 'cereal', true, now(), now()),
        (gen_random_uuid(), 'Tomato', '{"hi": "टमाटर", "ml": "തക്കാളി"}', 'Solanum lycopersicum', 'vegetable', true, now(), now()),
        (gen_random_uuid(), 'Onion', '{"hi": "प्याज", "ml": "ഉള്ളി"}', 'Allium cepa', 'vegetable', true, now(), now()),
        (gen_random_uuid(), 'Chilli', '{"hi": "मिर्च", "ml": "മുളക്"}', 'Capsicum annuum', 'vegetable', true, now(), now()),
        (gen_random_uuid(), 'Banana', '{"hi": "केला", "ml": "വാഴ"}', 'Musa spp.', 'fruit', true, now(), now()),
        (gen_random_uuid(), 'Cotton', '{"hi": "कपास"}', 'Gossypium hirsutum', 'cash_crop', true, now(), now()),
        (gen_random_uuid(), 'Sugarcane', '{"hi": "गन्ना"}', 'Saccharum officinarum', 'cash_crop', true, now(), now()),
        (gen_random_uuid(), 'Groundnut', '{"hi": "मूंगफली"}', 'Arachis hypogaea', 'oilseed', true, now(), now()),
        (gen_random_uuid(), 'Coconut', '{"ml": "തെങ്ങ്", "ta": "தென்னை"}', 'Cocos nucifera', 'plantation', true, now(), now()),
        (gen_random_uuid(), 'Black Pepper', '{"ml": "കുരുമുളക്"}', 'Piper nigrum', 'spice', true, now(), now())
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_cycles_sowing_date'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_plot_id'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_expected_harvest_date'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_cultivation_status'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_crop_id'), table_name='crop_cycles')
    op.drop_table('crop_cycles')
    op.drop_index(op.f('ix_plots_status'), table_name='plots')
    op.drop_index(op.f('ix_plots_farm_id'), table_name='plots')
    op.drop_table('plots')
    op.drop_index(op.f('ix_farms_status'), table_name='farms')
    op.drop_index(op.f('ix_farms_farmer_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_crop_master_category'), table_name='crop_master')
    op.drop_table('crop_master')
    # ### end Alembic commands ###

    # Autogenerate does NOT drop the Postgres ENUM types it creates inline
    # on a column (op.drop_table only drops the table, not types that may
    # still be referenced elsewhere) - found by actually running this
    # downgrade and hitting "type already exists" on the next upgrade.
    # Dropped explicitly here, in reverse dependency order, with
    # checkfirst=True so a partial/already-clean state doesn't error.
    bind = op.get_bind()
    sa.Enum(name='cultivation_status').drop(bind, checkfirst=True)
    sa.Enum(name='crop_season').drop(bind, checkfirst=True)
    sa.Enum(name='farm_status').drop(bind, checkfirst=True)
    sa.Enum(name='area_unit').drop(bind, checkfirst=True)
