"""create states and districts tables for location master data

Revision ID: 8813e01a2a4a
Revises: e44e3464afac
Create Date: 2026-08-23 17:22:22.482742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8813e01a2a4a'
down_revision: Union[str, None] = 'e44e3464afac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'name', name='uq_district_state_name')
    )
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    # ### end Alembic commands ###

    # Seed Andhra Pradesh and its current 26 districts (post-2022
    # reorganization). Other states are added the same way as the app
    # expands to them.
    op.execute("INSERT INTO states (code, name) VALUES ('AP', 'Andhra Pradesh')")
    op.execute(
        """
        INSERT INTO districts (state_id, name)
        SELECT s.id, d.name
        FROM (VALUES
            ('Srikakulam'),
            ('Parvathipuram Manyam'),
            ('Vizianagaram'),
            ('Visakhapatnam'),
            ('Anakapalli'),
            ('Alluri Sitharama Raju'),
            ('Kakinada'),
            ('East Godavari'),
            ('Konaseema'),
            ('West Godavari'),
            ('Eluru'),
            ('Krishna'),
            ('NTR'),
            ('Guntur'),
            ('Palnadu'),
            ('Bapatla'),
            ('Prakasam'),
            ('SPSR Nellore'),
            ('Kurnool'),
            ('Nandyal'),
            ('Anantapur'),
            ('Sri Sathya Sai'),
            ('YSR Kadapa'),
            ('Annamayya'),
            ('Chittoor'),
            ('Tirupati')
        ) AS d(name)
        CROSS JOIN (SELECT id FROM states WHERE code = 'AP') AS s
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('states')
    # ### end Alembic commands ###
