"""create crop photo session and crop photo tables

Revision ID: 8b83c52b7a23
Revises: 6bcb8d62ff76
Create Date: 2026-08-12 13:02:59.626429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b83c52b7a23'
down_revision: Union[str, None] = '6bcb8d62ff76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_photo_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_photo_sessions_crop_cycle_id'), 'crop_photo_sessions', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_crop_photo_sessions_farmer_id'), 'crop_photo_sessions', ['farmer_id'], unique=False)
    op.create_table('crop_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('client_upload_id', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_storage_key', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('capture_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('source', sa.Enum('camera', 'gallery', name='photo_source'), nullable=False),
    sa.Column('upload_status', sa.Enum('uploaded', 'failed', 'ready', 'deleted', name='photo_upload_status'), nullable=False),
    sa.Column('image_quality_status', sa.Enum('pending', 'accepted', 'rejected', name='photo_quality_status'), nullable=False),
    sa.Column('quality_reasons', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_crop_photos_file_size_positive'),
    sa.CheckConstraint('width_px > 0 AND height_px > 0', name='ck_crop_photos_dimensions_positive'),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['crop_photo_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_photos_crop_cycle_id'), 'crop_photos', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_crop_photos_farm_id'), 'crop_photos', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crop_photos_farmer_id'), 'crop_photos', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_crop_photos_plot_id'), 'crop_photos', ['plot_id'], unique=False)
    op.create_index(op.f('ix_crop_photos_session_id'), 'crop_photos', ['session_id'], unique=False)
    op.create_index(op.f('ix_crop_photos_upload_status'), 'crop_photos', ['upload_status'], unique=False)
    # Idempotency constraint (Requirement 22) - the actual mechanism that
    # makes a retried upload with the same client_upload_id impossible to
    # duplicate at the database level, not just in application code.
    op.create_unique_constraint(
        'uq_crop_photos_session_client_upload_id', 'crop_photos', ['session_id', 'client_upload_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_crop_photos_session_client_upload_id', 'crop_photos', type_='unique')
    op.drop_index(op.f('ix_crop_photos_upload_status'), table_name='crop_photos')
    op.drop_index(op.f('ix_crop_photos_session_id'), table_name='crop_photos')
    op.drop_index(op.f('ix_crop_photos_plot_id'), table_name='crop_photos')
    op.drop_index(op.f('ix_crop_photos_farmer_id'), table_name='crop_photos')
    op.drop_index(op.f('ix_crop_photos_farm_id'), table_name='crop_photos')
    op.drop_index(op.f('ix_crop_photos_crop_cycle_id'), table_name='crop_photos')
    op.drop_table('crop_photos')
    op.drop_index(op.f('ix_crop_photo_sessions_farmer_id'), table_name='crop_photo_sessions')
    op.drop_index(op.f('ix_crop_photo_sessions_crop_cycle_id'), table_name='crop_photo_sessions')
    op.drop_table('crop_photo_sessions')
    # ### end Alembic commands ###

    # Autogenerate does not drop the Postgres ENUM types it creates inline
    # on a column - learned the hard way in the previous migration (see
    # docs/DATABASE.md). Dropped explicitly here in reverse dependency order.
    bind = op.get_bind()
    sa.Enum(name='photo_quality_status').drop(bind, checkfirst=True)
    sa.Enum(name='photo_upload_status').drop(bind, checkfirst=True)
    sa.Enum(name='photo_source').drop(bind, checkfirst=True)
