"""create harvest marketplace buyer offer sale order and dispute tables

Revision ID: 8b8d84c1b065
Revises: 56f3c02490a8
Create Date: 2026-08-14 00:32:29.256141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b8d84c1b065'
down_revision: Union[str, None] = '56f3c02490a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('region', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('level', sa.Enum('high_demand', 'normal', 'low_demand', name='demand_level'), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_signals_crop_id'), 'demand_signals', ['crop_id'], unique=False)
    op.create_table('buyer_business_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('buyer_type', sa.Enum('business_buyer', 'wholesaler', 'processor', 'retailer', 'trader', 'institutional_buyer', name='buyer_type'), nullable=False),
    sa.Column('crops_purchased', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_requirements', sa.String(length=200), nullable=True),
    sa.Column('min_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_frequency', sa.String(length=100), nullable=True),
    sa.Column('collection_method', sa.String(length=50), nullable=True),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professional_id')
    )
    op.create_table('harvest_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('estimated_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quality_grade', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('planned', 'approaching', 'ready', 'harvested', 'listed', 'partially_sold', 'sold', 'cancelled', name='harvest_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_records_crop_cycle_id'), 'harvest_records', ['crop_cycle_id'], unique=True)
    op.create_index(op.f('ix_harvest_records_farmer_id'), 'harvest_records', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_harvest_records_status'), 'harvest_records', ['status'], unique=False)
    op.create_table('harvest_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('harvest_record_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quality_grade', sa.String(length=50), nullable=True),
    sa.Column('expected_availability_date', sa.Date(), nullable=True),
    sa.Column('service_area', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('delivery_option', sa.Enum('buyer_collection', 'farmer_delivery', 'third_party_logistics', name='collection_option'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['harvest_record_id'], ['harvest_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_listings_crop_id'), 'harvest_listings', ['crop_id'], unique=False)
    op.create_index(op.f('ix_harvest_listings_farmer_id'), 'harvest_listings', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_harvest_listings_harvest_record_id'), 'harvest_listings', ['harvest_record_id'], unique=False)
    op.create_table('buyer_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('harvest_listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quality_requirements', sa.String(length=200), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collection_terms', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'accepted', 'rejected', 'cancelled', 'completed', name='offer_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['harvest_listing_id'], ['harvest_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_offers_buyer_id'), 'buyer_offers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_offers_harvest_listing_id'), 'buyer_offers', ['harvest_listing_id'], unique=False)
    op.create_index(op.f('ix_buyer_offers_status'), 'buyer_offers', ['status'], unique=False)
    op.create_table('counter_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_offer_id', sa.UUID(), nullable=False),
    sa.Column('proposed_by', sa.Enum('buyer', 'farmer', name='negotiation_party'), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_offer_id'], ['buyer_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counter_offers_buyer_offer_id'), 'counter_offers', ['buyer_offer_id'], unique=False)
    op.create_table('sale_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('harvest_listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_offer_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quality_grade_snapshot', sa.String(length=50), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('charges', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('collection_method', sa.String(length=50), nullable=False),
    sa.Column('service_area_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exact_collection_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'preparing', 'ready_for_collection', 'collected', 'in_transit', 'delivered', 'payment_pending', 'paid', 'cancelled', 'disputed', 'completed', name='sale_order_status'), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['professional_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['buyer_offer_id'], ['buyer_offers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['harvest_listing_id'], ['harvest_listings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_orders_buyer_id'), 'sale_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_sale_orders_farmer_id'), 'sale_orders', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_sale_orders_harvest_listing_id'), 'sale_orders', ['harvest_listing_id'], unique=False)
    op.create_index(op.f('ix_sale_orders_status'), 'sale_orders', ['status'], unique=False)
    op.create_table('sale_disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_order_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_user_id', sa.UUID(), nullable=True),
    sa.Column('raised_by_role', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Enum('wrong_quantity', 'quality_disagreement', 'price_disagreement', 'payment_issue', 'delivery_issue', 'buyer_cancellation', 'farmer_cancellation', 'damaged_crop', 'other', name='sale_dispute_reason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'under_review', 'resolved', 'escalated', 'closed', name='sale_dispute_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_order_id'], ['sale_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_disputes_sale_order_id'), 'sale_disputes', ['sale_order_id'], unique=False)
    op.create_index(op.f('ix_sale_disputes_status'), 'sale_disputes', ['status'], unique=False)
    op.create_table('sale_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_order_id', sa.UUID(), nullable=False),
    sa.Column('given_by_user_id', sa.UUID(), nullable=True),
    sa.Column('given_by_role', sa.String(length=20), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['given_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_order_id'], ['sale_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_feedback_sale_order_id'), 'sale_feedback', ['sale_order_id'], unique=False)
    op.create_table('quality_disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_dispute_id', sa.UUID(), nullable=False),
    sa.Column('agreed_grade', sa.String(length=50), nullable=True),
    sa.Column('buyer_claimed_grade', sa.String(length=50), nullable=True),
    sa.Column('farmer_response', sa.Text(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('final_resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sale_dispute_id'], ['sale_disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_dispute_id')
    )
    op.add_column('deliveries', sa.Column('sale_order_id', sa.UUID(), nullable=True))
    op.alter_column('deliveries', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint(None, 'deliveries', ['sale_order_id'])
    op.create_foreign_key(None, 'deliveries', 'sale_orders', ['sale_order_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('sale_order_id', sa.UUID(), nullable=True))
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_payments_sale_order_id'), 'payments', ['sale_order_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'sale_orders', ['sale_order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_sale_order_id'), table_name='payments')
    op.drop_constraint('payments_sale_order_id_fkey', 'payments', type_='foreignkey')
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('payments', 'sale_order_id')
    op.drop_constraint('deliveries_sale_order_id_fkey', 'deliveries', type_='foreignkey')
    op.drop_constraint('deliveries_sale_order_id_key', 'deliveries', type_='unique')
    op.alter_column('deliveries', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('deliveries', 'sale_order_id')
    op.drop_table('quality_disputes')
    op.drop_index(op.f('ix_sale_feedback_sale_order_id'), table_name='sale_feedback')
    op.drop_table('sale_feedback')
    op.drop_index(op.f('ix_sale_disputes_status'), table_name='sale_disputes')
    op.drop_index(op.f('ix_sale_disputes_sale_order_id'), table_name='sale_disputes')
    op.drop_table('sale_disputes')
    op.drop_index(op.f('ix_sale_orders_status'), table_name='sale_orders')
    op.drop_index(op.f('ix_sale_orders_harvest_listing_id'), table_name='sale_orders')
    op.drop_index(op.f('ix_sale_orders_farmer_id'), table_name='sale_orders')
    op.drop_index(op.f('ix_sale_orders_buyer_id'), table_name='sale_orders')
    op.drop_table('sale_orders')
    op.drop_index(op.f('ix_counter_offers_buyer_offer_id'), table_name='counter_offers')
    op.drop_table('counter_offers')
    op.drop_index(op.f('ix_buyer_offers_status'), table_name='buyer_offers')
    op.drop_index(op.f('ix_buyer_offers_harvest_listing_id'), table_name='buyer_offers')
    op.drop_index(op.f('ix_buyer_offers_buyer_id'), table_name='buyer_offers')
    op.drop_table('buyer_offers')
    op.drop_index(op.f('ix_harvest_listings_harvest_record_id'), table_name='harvest_listings')
    op.drop_index(op.f('ix_harvest_listings_farmer_id'), table_name='harvest_listings')
    op.drop_index(op.f('ix_harvest_listings_crop_id'), table_name='harvest_listings')
    op.drop_table('harvest_listings')
    op.drop_index(op.f('ix_harvest_records_status'), table_name='harvest_records')
    op.drop_index(op.f('ix_harvest_records_farmer_id'), table_name='harvest_records')
    op.drop_index(op.f('ix_harvest_records_crop_cycle_id'), table_name='harvest_records')
    op.drop_table('harvest_records')
    op.drop_table('buyer_business_profiles')
    op.drop_index(op.f('ix_demand_signals_crop_id'), table_name='demand_signals')
    op.drop_table('demand_signals')
    # ### end Alembic commands ###

    # Enum types are not dropped by autogenerate - proactively fixed here
    # based on the lesson from every prior migration (see docs/DATABASE.md).
    bind = op.get_bind()
    sa.Enum(name='demand_level').drop(bind, checkfirst=True)
    sa.Enum(name='sale_dispute_status').drop(bind, checkfirst=True)
    sa.Enum(name='sale_dispute_reason').drop(bind, checkfirst=True)
    sa.Enum(name='sale_order_status').drop(bind, checkfirst=True)
    sa.Enum(name='negotiation_party').drop(bind, checkfirst=True)
    sa.Enum(name='offer_status').drop(bind, checkfirst=True)
    sa.Enum(name='collection_option').drop(bind, checkfirst=True)
    sa.Enum(name='harvest_status').drop(bind, checkfirst=True)
    sa.Enum(name='buyer_type').drop(bind, checkfirst=True)
