"""create mandals and villages tables and wire farm location fields

Revision ID: 90c85f85e7f8
Revises: 8813e01a2a4a
Create Date: 2026-08-23 18:39:31.067458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c85f85e7f8'
down_revision: Union[str, None] = '8813e01a2a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'name', name='uq_mandal_district_name')
    )
    op.create_index(op.f('ix_mandals_district_id'), 'mandals', ['district_id'], unique=False)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandal_id', 'name', name='uq_village_mandal_name')
    )
    op.create_index(op.f('ix_villages_mandal_id'), 'villages', ['mandal_id'], unique=False)
    op.add_column('farms', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('farms', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('farms', sa.Column('mandal_id', sa.Integer(), nullable=True))
    op.add_column('farms', sa.Column('village_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_farms_district_id'), 'farms', ['district_id'], unique=False)
    op.create_index(op.f('ix_farms_mandal_id'), 'farms', ['mandal_id'], unique=False)
    op.create_index(op.f('ix_farms_state_id'), 'farms', ['state_id'], unique=False)
    op.create_index(op.f('ix_farms_village_id'), 'farms', ['village_id'], unique=False)
    # Named explicitly (autogenerate leaves these unnamed, which is
    # silently accepted on create but fails on drop_constraint during
    # downgrade - the same class of bug already hit and fixed in the
    # Phase 29/31 migrations; naming them up front avoids repeating it).
    op.create_foreign_key('fk_farms_district_id_districts', 'farms', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_farms_village_id_villages', 'farms', 'villages', ['village_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_farms_mandal_id_mandals', 'farms', 'mandals', ['mandal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_farms_state_id_states', 'farms', 'states', ['state_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_farms_district_id_districts', 'farms', type_='foreignkey')
    op.drop_constraint('fk_farms_village_id_villages', 'farms', type_='foreignkey')
    op.drop_constraint('fk_farms_mandal_id_mandals', 'farms', type_='foreignkey')
    op.drop_constraint('fk_farms_state_id_states', 'farms', type_='foreignkey')
    op.drop_index(op.f('ix_farms_village_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_state_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_mandal_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_district_id'), table_name='farms')
    op.drop_column('farms', 'village_id')
    op.drop_column('farms', 'mandal_id')
    op.drop_column('farms', 'district_id')
    op.drop_column('farms', 'state_id')
    op.drop_index(op.f('ix_villages_mandal_id'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_mandals_district_id'), table_name='mandals')
    op.drop_table('mandals')
    # ### end Alembic commands ###
