"""create crop varieties table and add variety_id to crop_cycles

Phase 1: introduces CropVariety as a structured, crop-scoped reference
entity, and adds a nullable variety_id FK on crop_cycles. Purely
additive - CropCycle.seed_variety (free text) is untouched, still
nullable, still independently usable. No existing column, index, or
constraint is modified. Does not touch harvest_records or the Phase 0
migration in any way.

Revision ID: a99bd945587b
Revises: da873270b431
Create Date: 2026-08-18 06:00:21.448200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a99bd945587b'
down_revision: Union[str, None] = 'da873270b431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_varieties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('typical_duration_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'name', name='uq_crop_varieties_crop_id_name')
    )
    op.create_index(op.f('ix_crop_varieties_crop_id'), 'crop_varieties', ['crop_id'], unique=False)
    op.add_column('crop_cycles', sa.Column('variety_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_crop_cycles_variety_id'), 'crop_cycles', ['variety_id'], unique=False)
    op.create_foreign_key('crop_cycles_variety_id_fkey', 'crop_cycles', 'crop_varieties', ['variety_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crop_cycles_variety_id_fkey', 'crop_cycles', type_='foreignkey')
    op.drop_index(op.f('ix_crop_cycles_variety_id'), table_name='crop_cycles')
    op.drop_column('crop_cycles', 'variety_id')
    op.drop_index(op.f('ix_crop_varieties_crop_id'), table_name='crop_varieties')
    op.drop_table('crop_varieties')
    # ### end Alembic commands ###
