"""create weather snapshot notification and notification preference tables

Revision ID: c5ad448c722a
Revises: 4cac6105f1a7
Create Date: 2026-08-13 00:34:09.663929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ad448c722a'
down_revision: Union[str, None] = '4cac6105f1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('weather_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('rain_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('crop_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('disease_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('audio_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('general_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('weather_alert', 'rain_alert', 'heavy_rain_alert', 'crop_alert', 'disease_alert', 'harvest_alert', name='notification_category'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='notification_priority'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('dedup_key', sa.String(length=300), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=100), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id', 'dedup_key', name='uq_notifications_farmer_dedup_key')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_farmer_id'), 'notifications', ['farmer_id'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_type', sa.Enum('current', 'forecast', name='weather_snapshot_type'), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('feels_like_c', sa.Float(), nullable=True),
    sa.Column('temperature_min_c', sa.Float(), nullable=True),
    sa.Column('temperature_max_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('rain_probability_percent', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_degrees', sa.Float(), nullable=True),
    sa.Column('condition_code', sa.String(length=50), nullable=True),
    sa.Column('sunrise', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sunset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_expires_at'), 'weather_snapshots', ['expires_at'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_farm_id'), 'weather_snapshots', ['farm_id'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_snapshot_type'), 'weather_snapshots', ['snapshot_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_snapshots_snapshot_type'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_farm_id'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_expires_at'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_notifications_farmer_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###

    # Enum types are not dropped by autogenerate - proactively fixed here
    # based on the lesson from prior migrations (see docs/DATABASE.md).
    bind = op.get_bind()
    sa.Enum(name='notification_priority').drop(bind, checkfirst=True)
    sa.Enum(name='notification_category').drop(bind, checkfirst=True)
    sa.Enum(name='weather_snapshot_type').drop(bind, checkfirst=True)
