"""create treatment records and follow ups for phase 34 effectiveness tracking

Revision ID: d594abebc57f
Revises: 0f96c82c2a21
Create Date: 2026-08-22 01:52:37.782263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd594abebc57f'
down_revision: Union[str, None] = '0f96c82c2a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('before_analysis_id', sa.UUID(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['before_analysis_id'], ['ai_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['crop_health_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_records_crop_cycle_id'), 'treatment_records', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_treatment_records_farmer_id'), 'treatment_records', ['farmer_id'], unique=False)
    op.create_table('treatment_follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('treatment_id', sa.UUID(), nullable=False),
    sa.Column('after_analysis_id', sa.UUID(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['after_analysis_id'], ['ai_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_follow_ups_farmer_id'), 'treatment_follow_ups', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_treatment_follow_ups_treatment_id'), 'treatment_follow_ups', ['treatment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_treatment_follow_ups_treatment_id'), table_name='treatment_follow_ups')
    op.drop_index(op.f('ix_treatment_follow_ups_farmer_id'), table_name='treatment_follow_ups')
    op.drop_table('treatment_follow_ups')
    op.drop_index(op.f('ix_treatment_records_farmer_id'), table_name='treatment_records')
    op.drop_index(op.f('ix_treatment_records_crop_cycle_id'), table_name='treatment_records')
    op.drop_table('treatment_records')
    # ### end Alembic commands ###
