"""remove unique constraint on harvest_records crop_cycle_id

Phase 0 fix: HarvestRecord.crop_cycle_id was unique, forcing exactly one
harvest per crop cycle. Real crops with repeated picking (tomato, chilli,
okra, brinjal, beans, cucumber) need multiple HarvestRecord rows per
CropCycle. This migration only swaps the index from unique to non-unique -
no columns added/removed, no data touched, table not recreated.

Downgrade will fail if any crop cycle by then has more than one harvest
record (recreating the unique index is only valid if the data satisfies
it) - this is correct, expected behavior, not a bug in the downgrade.

Revision ID: da873270b431
Revises: 360232fb3de0
Create Date: 2026-08-18 05:17:19.933975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da873270b431'
down_revision: Union[str, None] = '360232fb3de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_harvest_records_crop_cycle_id', table_name='harvest_records')
    op.create_index(op.f('ix_harvest_records_crop_cycle_id'), 'harvest_records', ['crop_cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harvest_records_crop_cycle_id'), table_name='harvest_records')
    op.create_index('ix_harvest_records_crop_cycle_id', 'harvest_records', ['crop_cycle_id'], unique=True)
    # ### end Alembic commands ###
