"""create professional network and case management tables

Revision ID: dc30b6c2b356
Revises: c5ad448c722a
Create Date: 2026-08-13 00:56:41.748775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc30b6c2b356'
down_revision: Union[str, None] = 'c5ad448c722a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('language_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crop_specialization_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disease_specialization_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('service_area', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', 'suspended', 'expired', name='professional_verification_status'), nullable=False),
    sa.Column('availability_status', sa.Enum('available', 'busy', 'offline', name='professional_availability_status'), nullable=False),
    sa.Column('max_active_cases', sa.Integer(), nullable=False),
    sa.Column('completed_case_count', sa.Integer(), nullable=False),
    sa.Column('is_test_account', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_professional_profiles_availability_status'), 'professional_profiles', ['availability_status'], unique=False)
    op.create_index(op.f('ix_professional_profiles_role'), 'professional_profiles', ['role'], unique=False)
    op.create_index(op.f('ix_professional_profiles_verification_status'), 'professional_profiles', ['verification_status'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('verify', 'reject', 'suspend', 'reactivate', name='verification_action'), nullable=False),
    sa.Column('performed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_professional_id'), 'verification_records', ['professional_id'], unique=False)
    op.create_table('crop_health_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('crop_photo_id', sa.UUID(), nullable=True),
    sa.Column('ai_analysis_id', sa.UUID(), nullable=True),
    sa.Column('requested_professional_role', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Enum('farmer_requested', 'ai_low_confidence', 'ai_unknown', 'farmer_dispute', name='case_reason'), nullable=False),
    sa.Column('status', sa.Enum('open', 'waiting_for_assignment', 'assigned', 'in_review', 'needs_more_information', 'verified', 'rejected', 'escalated', 'closed', 'cancelled', name='case_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='case_priority'), nullable=False),
    sa.Column('final_verified_class', sa.String(length=150), nullable=True),
    sa.Column('final_verification_source', sa.String(length=50), nullable=True),
    sa.Column('second_opinion_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_analysis_id'], ['ai_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_photo_id'], ['crop_photos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_health_cases_crop_cycle_id'), 'crop_health_cases', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_crop_health_cases_farmer_id'), 'crop_health_cases', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_crop_health_cases_status'), 'crop_health_cases', ['status'], unique=False)
    op.create_table('case_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'expired', 'completed', name='assignment_status'), nullable=False),
    sa.Column('assignment_reason', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['crop_health_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'professional_id', name='uq_case_assignment_case_professional')
    )
    op.create_index(op.f('ix_case_assignments_case_id'), 'case_assignments', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_assignments_professional_id'), 'case_assignments', ['professional_id'], unique=False)
    op.create_index(op.f('ix_case_assignments_status'), 'case_assignments', ['status'], unique=False)
    op.create_table('case_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('shared_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['crop_health_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('photo_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('crop_photo_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['crop_health_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_photo_id'], ['crop_photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_access_grants_case_id'), 'photo_access_grants', ['case_id'], unique=False)
    op.create_index(op.f('ix_photo_access_grants_crop_photo_id'), 'photo_access_grants', ['crop_photo_id'], unique=False)
    op.create_index(op.f('ix_photo_access_grants_professional_id'), 'photo_access_grants', ['professional_id'], unique=False)
    op.create_table('professional_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['crop_health_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_professional_feedback_professional_id'), 'professional_feedback', ['professional_id'], unique=False)
    op.create_table('case_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_role', sa.Enum('expert', 'field_agent', name='reviewer_role'), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('alternative_disease_name', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['case_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['crop_health_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_reviews_case_id'), 'case_reviews', ['case_id'], unique=False)
    # ### end Alembic commands ###

    # Seed the new 'trader' role - field_agent, expert, dealer, admin were
    # already seeded in the Auth phase migration.
    op.execute("INSERT INTO roles (code) VALUES ('trader')")


def downgrade() -> None:
    # Undo the role seed first (Requirement: downgrade must fully reverse
    # upgrade) - found by actually running downgrade then upgrade again
    # and hitting a duplicate-key error on 'trader'. The `roles` table
    # itself isn't touched by this migration's table drops, so its seeded
    # row needed an explicit removal here.
    op.execute("DELETE FROM roles WHERE code = 'trader'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_reviews_case_id'), table_name='case_reviews')
    op.drop_table('case_reviews')
    op.drop_index(op.f('ix_professional_feedback_professional_id'), table_name='professional_feedback')
    op.drop_table('professional_feedback')
    op.drop_index(op.f('ix_photo_access_grants_professional_id'), table_name='photo_access_grants')
    op.drop_index(op.f('ix_photo_access_grants_crop_photo_id'), table_name='photo_access_grants')
    op.drop_index(op.f('ix_photo_access_grants_case_id'), table_name='photo_access_grants')
    op.drop_table('photo_access_grants')
    op.drop_table('case_consents')
    op.drop_index(op.f('ix_case_assignments_status'), table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_professional_id'), table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_case_id'), table_name='case_assignments')
    op.drop_table('case_assignments')
    op.drop_index(op.f('ix_crop_health_cases_status'), table_name='crop_health_cases')
    op.drop_index(op.f('ix_crop_health_cases_farmer_id'), table_name='crop_health_cases')
    op.drop_index(op.f('ix_crop_health_cases_crop_cycle_id'), table_name='crop_health_cases')
    op.drop_table('crop_health_cases')
    op.drop_index(op.f('ix_verification_records_professional_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_professional_profiles_verification_status'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_role'), table_name='professional_profiles')
    op.drop_index(op.f('ix_professional_profiles_availability_status'), table_name='professional_profiles')
    op.drop_table('professional_profiles')
    # ### end Alembic commands ###

    # Enum types are not dropped by autogenerate - proactively fixed here
    # based on the lesson from every prior migration (see docs/DATABASE.md).
    bind = op.get_bind()
    sa.Enum(name='reviewer_role').drop(bind, checkfirst=True)
    sa.Enum(name='assignment_status').drop(bind, checkfirst=True)
    sa.Enum(name='case_priority').drop(bind, checkfirst=True)
    sa.Enum(name='case_status').drop(bind, checkfirst=True)
    sa.Enum(name='case_reason').drop(bind, checkfirst=True)
    sa.Enum(name='verification_action').drop(bind, checkfirst=True)
    sa.Enum(name='professional_availability_status').drop(bind, checkfirst=True)
    sa.Enum(name='professional_verification_status').drop(bind, checkfirst=True)
