"""create advisory feedback table for phase 39 personalization foundation

Revision ID: e44e3464afac
Revises: d594abebc57f
Create Date: 2026-08-22 10:58:10.931237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44e3464afac'
down_revision: Union[str, None] = 'd594abebc57f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisory_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('crop_assistant', 'risk_score', 'weather_action', 'irrigation_intelligence', 'treatment_recommendation', name='advisory_source_type'), nullable=False),
    sa.Column('source_reference', sa.String(length=100), nullable=True),
    sa.Column('feedback_type', sa.Enum('helpful', 'not_helpful', 'wrong', 'need_expert', name='advisory_feedback_type'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisory_feedback_crop_cycle_id'), 'advisory_feedback', ['crop_cycle_id'], unique=False)
    op.create_index(op.f('ix_advisory_feedback_farmer_id'), 'advisory_feedback', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_advisory_feedback_source_type'), 'advisory_feedback', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisory_feedback_source_type'), table_name='advisory_feedback')
    op.drop_index(op.f('ix_advisory_feedback_farmer_id'), table_name='advisory_feedback')
    op.drop_index(op.f('ix_advisory_feedback_crop_cycle_id'), table_name='advisory_feedback')
    op.drop_table('advisory_feedback')
    # ### end Alembic commands ###

    # Enum types are not dropped by op.drop_table (the same lesson
    # learned in every prior phase's migrations) - fixed here explicitly.
    bind = op.get_bind()
    sa.Enum(name='advisory_feedback_type').drop(bind, checkfirst=True)
    sa.Enum(name='advisory_source_type').drop(bind, checkfirst=True)
